### ISSUE TITLE
显示适配成功，但模块选项未出现

### ISSUE THREAD

**Issue by AlexiaFate** [Xposed-Modules-Repo/com.rong862.bear#5]
设备是华为matepad11，模块版本为1.9.0，抖音版本为24.1.0，使用lspatch打包了内置版。
不知道是不是因为在pad上抖音为大屏班的缘故。

**Comment by Zbw1334852854** [comment]
> 设备是华为matepad11，模块版本为1.9.0，抖音版本为24.1.0，使用lspatch打包了内置版。
> 不知道是不是因为在pad上抖音为大屏班的缘故。

我的也不显示，也是打包了内置版
